CREATE TABLE dormitory
(
    id_dormitory         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    address              VARCHAR(255),
    available_places     SMALLINT                                NOT NULL,
    all_places           SMALLINT                                NOT NULL,
    dormitory_rooms_type SMALLINT                                NOT NULL,
    rating               DOUBLE PRECISION,
    description          VARCHAR(255),
    fk_id_university     BIGINT,
    CONSTRAINT pk_dormitory PRIMARY KEY (id_dormitory)
);

CREATE TABLE university
(
    id_university      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name               VARCHAR(255)                            NOT NULL,
    address            VARCHAR(255)                            NOT NULL,
    rating             DOUBLE PRECISION                        NOT NULL,
    email              VARCHAR(255)                            NOT NULL,
    website            VARCHAR(255)                            NOT NULL,
    phone_number       VARCHAR(255)                            NOT NULL,
    government_funding BOOLEAN                                 NOT NULL,
    military_center    BOOLEAN                                 NOT NULL,
    description        VARCHAR(255),
    CONSTRAINT pk_university PRIMARY KEY (id_university)
);

ALTER TABLE university
    ADD CONSTRAINT uc_university_address UNIQUE (address);

ALTER TABLE university
    ADD CONSTRAINT uc_university_email UNIQUE (email);

ALTER TABLE university
    ADD CONSTRAINT uc_university_name UNIQUE (name);

ALTER TABLE university
    ADD CONSTRAINT uc_university_phone_number UNIQUE (phone_number);

ALTER TABLE university
    ADD CONSTRAINT uc_university_website UNIQUE (website);

ALTER TABLE dormitory
    ADD CONSTRAINT FK_DORMITORY_ON_FK_ID_UNIVERSITY FOREIGN KEY (fk_id_university) REFERENCES university (id_university) ON DELETE CASCADE;