CREATE TABLE culture_house
(
    id_culture_house BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    address          VARCHAR(255)                            NOT NULL,
    rating           DOUBLE PRECISION,
    schedule         VARCHAR(255),
    fk_id_university BIGINT,
    CONSTRAINT pk_culture_house PRIMARY KEY (id_culture_house)
);

CREATE TABLE culture_house_activity
(
    id_culture_house_activity SMALLINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name_activity             VARCHAR(255)                              NOT NULL,
    description               VARCHAR(255),
    fk_id_culture_house       BIGINT,
    CONSTRAINT pk_culture_house_activity PRIMARY KEY (id_culture_house_activity)
);

CREATE TABLE department
(
    id_department   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name_department VARCHAR(255),
    fk_id_faculty   INTEGER,
    CONSTRAINT pk_department PRIMARY KEY (id_department)
);

CREATE TABLE dining_room
(
    id_dining_room   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    address          VARCHAR(255),
    rating           DOUBLE PRECISION,
    schedule         VARCHAR(255),
    fk_id_university BIGINT,
    CONSTRAINT pk_dining_room PRIMARY KEY (id_dining_room)
);

CREATE TABLE direction_subjects
(
    id_educational_direction BIGINT NOT NULL,
    subject                  VARCHAR(255)
);

CREATE TABLE dormitory
(
    id_dormitory         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    address              VARCHAR(255),
    available_places     SMALLINT                                NOT NULL,
    all_places           SMALLINT                                NOT NULL,
    dormitory_rooms_type SMALLINT                                NOT NULL,
    rating               DOUBLE PRECISION,
    description          VARCHAR(255),
    fk_id_university     BIGINT,
    CONSTRAINT pk_dormitory PRIMARY KEY (id_dormitory)
);

CREATE TABLE educational_direction
(
    id_educational_direction   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    count_places               BIGINT                                  NOT NULL,
    educational_type           SMALLINT,
    educational_cost           BIGINT,
    name_educational_direction VARCHAR(255)                            NOT NULL,
    fk_id_department           BIGINT,
    CONSTRAINT pk_educational_direction PRIMARY KEY (id_educational_direction)
);

CREATE TABLE faculty
(
    id_faculty       INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name_faculty     VARCHAR(255)                             NOT NULL,
    phone_number     VARCHAR(255)                             NOT NULL,
    description      VARCHAR(255),
    fk_id_university BIGINT,
    CONSTRAINT pk_faculty PRIMARY KEY (id_faculty)
);

CREATE TABLE gym
(
    id_gym           SMALLINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    address          VARCHAR(255)                              NOT NULL,
    rating           DOUBLE PRECISION                          NOT NULL,
    schedule         VARCHAR(255),
    fk_id_university BIGINT,
    CONSTRAINT pk_gym PRIMARY KEY (id_gym)
);

CREATE TABLE gym_activity
(
    id_gym_activity      SMALLINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name_activity        VARCHAR(255),
    gym_activity_trainer VARCHAR(255),
    fk_id_gym            SMALLINT,
    CONSTRAINT pk_gym_activity PRIMARY KEY (id_gym_activity)
);

CREATE TABLE laboratory
(
    id_laboratory           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    laboratory_count_places SMALLINT,
    laboratory_name         VARCHAR(255)                            NOT NULL,
    fk_id_department        BIGINT,
    CONSTRAINT pk_laboratory PRIMARY KEY (id_laboratory)
);

CREATE TABLE laboratory_assistant
(
    id_laboratory_assistant      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    hours_in_laboratory_per_week SMALLINT                                NOT NULL,
    position                     VARCHAR(255)                            NOT NULL,
    full_name                    VARCHAR(255)                            NOT NULL,
    experience_years             SMALLINT                                NOT NULL,
    fk_id_laboratory             BIGINT,
    CONSTRAINT pk_laboratory_assistant PRIMARY KEY (id_laboratory_assistant)
);

CREATE TABLE person
(
    id_person BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username  VARCHAR(255),
    password  VARCHAR(255),
    CONSTRAINT pk_person PRIMARY KEY (id_person)
);

CREATE TABLE student
(
    id_student            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    fk_id_study_group     BIGINT,
    free_education_cost   BOOLEAN                                 NOT NULL,
    student_passing_score SMALLINT                                NOT NULL,
    CONSTRAINT pk_student PRIMARY KEY (id_student)
);

CREATE TABLE study_group
(
    id_study_group              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    fk_id_educational_direction BIGINT,
    CONSTRAINT pk_study_group PRIMARY KEY (id_study_group)
);

CREATE TABLE university
(
    id_university      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name               VARCHAR(255)                            NOT NULL,
    address            VARCHAR(255)                            NOT NULL,
    rating             DOUBLE PRECISION                        NOT NULL,
    email              VARCHAR(255)                            NOT NULL,
    website            VARCHAR(255)                            NOT NULL,
    phone_number       VARCHAR(255)                            NOT NULL,
    government_funding BOOLEAN                                 NOT NULL,
    military_center    BOOLEAN                                 NOT NULL,
    description        VARCHAR(255),
    CONSTRAINT pk_university PRIMARY KEY (id_university)
);

ALTER TABLE culture_house
    ADD CONSTRAINT uc_culture_house_fk_id_university UNIQUE (fk_id_university);

ALTER TABLE person
    ADD CONSTRAINT uc_person_username UNIQUE (username);

ALTER TABLE university
    ADD CONSTRAINT uc_university_address UNIQUE (address);

ALTER TABLE university
    ADD CONSTRAINT uc_university_email UNIQUE (email);

ALTER TABLE university
    ADD CONSTRAINT uc_university_name UNIQUE (name);

ALTER TABLE university
    ADD CONSTRAINT uc_university_phone_number UNIQUE (phone_number);

ALTER TABLE university
    ADD CONSTRAINT uc_university_website UNIQUE (website);

ALTER TABLE culture_house_activity
    ADD CONSTRAINT FK_CULTURE_HOUSE_ACTIVITY_ON_FK_ID_CULTURE_HOUSE FOREIGN KEY (fk_id_culture_house) REFERENCES culture_house (id_culture_house) ON DELETE CASCADE;

ALTER TABLE culture_house
    ADD CONSTRAINT FK_CULTURE_HOUSE_ON_FK_ID_UNIVERSITY FOREIGN KEY (fk_id_university) REFERENCES university (id_university);

ALTER TABLE department
    ADD CONSTRAINT FK_DEPARTMENT_ON_FK_ID_FACULTY FOREIGN KEY (fk_id_faculty) REFERENCES faculty (id_faculty);

ALTER TABLE dining_room
    ADD CONSTRAINT FK_DINING_ROOM_ON_FK_ID_UNIVERSITY FOREIGN KEY (fk_id_university) REFERENCES university (id_university) ON DELETE CASCADE;

ALTER TABLE dormitory
    ADD CONSTRAINT FK_DORMITORY_ON_FK_ID_UNIVERSITY FOREIGN KEY (fk_id_university) REFERENCES university (id_university) ON DELETE CASCADE;

ALTER TABLE educational_direction
    ADD CONSTRAINT FK_EDUCATIONAL_DIRECTION_ON_FK_ID_DEPARTMENT FOREIGN KEY (fk_id_department) REFERENCES department (id_department);

ALTER TABLE faculty
    ADD CONSTRAINT FK_FACULTY_ON_FK_ID_UNIVERSITY FOREIGN KEY (fk_id_university) REFERENCES university (id_university) ON DELETE CASCADE;

ALTER TABLE gym_activity
    ADD CONSTRAINT FK_GYM_ACTIVITY_ON_FK_ID_GYM FOREIGN KEY (fk_id_gym) REFERENCES gym (id_gym) ON DELETE CASCADE;

ALTER TABLE gym
    ADD CONSTRAINT FK_GYM_ON_FK_ID_UNIVERSITY FOREIGN KEY (fk_id_university) REFERENCES university (id_university) ON DELETE CASCADE;

ALTER TABLE laboratory_assistant
    ADD CONSTRAINT FK_LABORATORY_ASSISTANT_ON_FK_ID_LABORATORY FOREIGN KEY (fk_id_laboratory) REFERENCES laboratory (id_laboratory);

ALTER TABLE laboratory
    ADD CONSTRAINT FK_LABORATORY_ON_FK_ID_DEPARTMENT FOREIGN KEY (fk_id_department) REFERENCES department (id_department);

ALTER TABLE student
    ADD CONSTRAINT FK_STUDENT_ON_FK_ID_STUDY_GROUP FOREIGN KEY (fk_id_study_group) REFERENCES study_group (id_study_group);

ALTER TABLE study_group
    ADD CONSTRAINT FK_STUDY_GROUP_ON_FK_ID_EDUCATIONAL_DIRECTION FOREIGN KEY (fk_id_educational_direction) REFERENCES educational_direction (id_educational_direction);

ALTER TABLE direction_subjects
    ADD CONSTRAINT fk_direction_subjects_on_educational_direction FOREIGN KEY (id_educational_direction) REFERENCES educational_direction (id_educational_direction);